# Generated by Django 5.2.11 on 2026-02-04 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('iso3', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('iso2', models.CharField(blank=True, max_length=2, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active')], default='DRAFT', max_length=20)),
                ('currency_mode', models.CharField(choices=[('LIST', 'List (specific currencies)'), ('ALL_FIAT', 'All Fiat currencies')], default='ALL_FIAT', max_length=20)),
                ('google_sheet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['provider_name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_game_id', models.CharField(blank=True, max_length=255, null=True)),
                ('game_title', models.CharField(max_length=255)),
                ('game_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('game_type', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('game_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('subtype', models.CharField(blank=True, max_length=100, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('fun_mode', models.BooleanField(default=False)),
                ('rtp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('volatility', models.CharField(blank=True, max_length=50, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('themes', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, max_length=500, null=True)),
                ('api_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='providers.provider')),
            ],
            options={
                'ordering': ['game_title'],
            },
        ),
        migrations.CreateModel(
            name='FiatCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10)),
                ('display', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiat_currencies', to='providers.provider')),
            ],
            options={
                'verbose_name_plural': 'Fiat currencies',
                'ordering': ['currency_code'],
                'unique_together': {('provider', 'currency_code')},
            },
        ),
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=20)),
                ('display', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_currencies', to='providers.provider')),
            ],
            options={
                'verbose_name_plural': 'Crypto currencies',
                'ordering': ['currency_code'],
                'unique_together': {('provider', 'currency_code')},
            },
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10)),
                ('restriction_type', models.CharField(choices=[('RESTRICTED', 'Restricted'), ('REGULATED', 'Regulated')], default='RESTRICTED', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='providers.provider')),
            ],
            options={
                'ordering': ['country_code'],
                'unique_together': {('provider', 'country_code')},
            },
        ),
    ]
