# Generated by Django 5.2.11 on 2026-02-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
