# Generated by Django 5.2.11 on 2026-02-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_provider_logo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='logo_url',
            new_name='logo_url_dark',
        ),
        migrations.AddField(
            model_name='provider',
            name='logo_url_light',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
